language: ruby
rvm:
  - rbx-2.1.1
  - ruby-head
  - 1.8.7
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4
  - jruby-18mode
  - jruby-19mode
  - jruby-head
before_install:
 - gem update bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: 1.8.7
    - rvm: rbx-2.1.1
    - rvm: 1.9.3
    - rvm: 1.9.2