shop_id: tshop0001
shop_pass: 1
site_id: tsite0001
site_pass: 1
host: pt01.mul-pay.jp
token_member_id: 1
token: 1

remittance:
  shop_id: rshop00000001
  shop_pass: 1234abcd
  host: test-remittance.gmopg.jp
